// Type declaration for the prebuilt Emscripten module `osc-engine.mjs`.
// Hand-written; the `.mjs`/`.wasm` are generated by native/build.mjs from the
// pinned RAC submodule. Kept in sync with native/osc_engine_embind.cpp.

/** Emscripten in-memory filesystem (subset actually used by the loader). */
export interface OscEngineFS {
  writeFile(path: string, data: string | Uint8Array): void
  readFile(path: string, opts: { encoding: 'utf8' }): string
  mkdirTree(path: string): void
  unlink(path: string): void
  analyzePath(path: string): { exists: boolean }
}

/** The embind surface exported by osc_engine_embind.cpp. All data-only. */
export interface OscEngineModule {
  /** Capability probe → JSON `{ engine, engineCommit, oscVersions[], xsd }`. */
  describe(): string
  /** Validate the .xosc at MEMFS `mainPath` → JSON diagnostics. */
  validate(mainPath: string): string
  /** Re-serialize the parsed tree at `mainPath` back to a .xosc string. */
  roundtripExport(mainPath: string): string
  /** Author a minimal scenario from scratch via the typed writer factory. */
  authorMinimal(): string
  /**
   * Author a `.xosc` from a resolved engine-tree JSON via the typed writer
   * factory + model-generated exporter. Returns the XML, or a JSON
   * `{"fatal":…}` object on an authoring fault.
   */
  author(treeJson: string): string
  /** Emscripten MEMFS handle (present because the module forces FILESYSTEM). */
  FS: OscEngineFS
}

/** Instantiate the WASM module (async — compiles + instantiates the binary). */
declare const createOscEngine: (moduleArg?: Record<string, unknown>) => Promise<OscEngineModule>
export default createOscEngine
