/**
 * Drift guard for `artifacts/openscenario/openscenario.shacl.ttl` — the
 * cut-in-archetype SHACL excerpt the scene-authoring prompt embeds
 * (`packages/llm/src/authoring/scene-prompt.ts`).
 *
 * That file is GENERATED by `scripts/derive-openscenario-authoring-shacl.mjs`
 * from the pinned OMB v0.4.0 OpenSCENARIO ontology (`.ontology/imports/openscenario/openscenario.owl.ttl`).
 * This test reads both independently and asserts the committed artifact's
 * `sh:in` enum lists still match what the pinned ontology's `owl:oneOf`
 * declares — the exact regression this guards against: the artifact's
 * VehicleCategory enum once hand-transcribed only 10 of ASAM's 21 real values
 * and nothing caught the gap until this comparison existed.
 *
 * [OWL2] OWL 2 Web Ontology Language (docs/specs/references/owl2-syntax.md).
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import type { Quad } from '@rdfjs/types'
import { Parser as N3Parser } from 'n3'
import { describe, expect, it } from 'vitest'

import { getWorkspaceRoot } from '../sources.js'

const root = getWorkspaceRoot()
const pinnedOntologyPath = join(
  root,
  '.ontology',
  'imports',
  'openscenario',
  'openscenario.owl.ttl'
)
const artifactPath = join(root, 'artifacts', 'openscenario', 'openscenario.shacl.ttl')

const RDF = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
const RDFS = 'http://www.w3.org/2000/01/rdf-schema#'
const OWL = 'http://www.w3.org/2002/07/owl#'

function resolveList(quads: Quad[], headNode: string): string[] {
  const byNode = new Map<string, { first?: string; rest?: string }>()
  for (const q of quads) {
    if (q.subject.termType !== 'BlankNode' && q.subject.termType !== 'NamedNode') continue
    const entry = byNode.get(q.subject.value) ?? {}
    if (q.predicate.value === `${RDF}first`) entry.first = q.object.value
    if (q.predicate.value === `${RDF}rest`) entry.rest = q.object.value
    byNode.set(q.subject.value, entry)
  }
  const values: string[] = []
  let node: string | undefined = headNode
  while (node && node !== `${RDF}nil`) {
    const entry = byNode.get(node)
    if (!entry) break
    if (entry.first !== undefined) values.push(entry.first)
    node = entry.rest
  }
  return values
}

/** The pinned ontology's `owl:oneOf` list for a named `rdfs:Datatype`. */
function pinnedEnum(label: string): string[] {
  const quads = new N3Parser().parse(readFileSync(pinnedOntologyPath, 'utf-8'))
  const datatype = quads.find(
    (q) =>
      q.predicate.value === `${RDF}type` &&
      q.object.value === `${RDFS}Datatype` &&
      quads.some(
        (l) =>
          l.subject.value === q.subject.value &&
          l.predicate.value === `${RDFS}label` &&
          l.object.value === label
      )
  )
  if (!datatype) throw new Error(`no rdfs:Datatype labelled "${label}" in the pinned ontology`)
  const oneOf = quads.find(
    (q) => q.subject.value === datatype.subject.value && q.predicate.value === `${OWL}oneOf`
  )
  if (!oneOf) throw new Error(`"${label}" declares no owl:oneOf`)
  return resolveList(quads, oneOf.object.value).sort()
}

/** The committed artifact's `sh:in ( ... )` list immediately following a marker line. */
function artifactEnum(propertyPath: string): string[] {
  const content = readFileSync(artifactPath, 'utf-8')
  const marker = `sh:path openscenario:${propertyPath}`
  const idx = content.indexOf(marker)
  if (idx < 0) throw new Error(`no property shape for "${propertyPath}" in the committed artifact`)
  const window = content.slice(idx, idx + 2000)
  const match = /sh:in\s*\(([^)]*)\)/.exec(window)
  if (!match) throw new Error(`no sh:in list following "${propertyPath}" in the committed artifact`)
  return [...match[1]!.matchAll(/"([^"]*)"/g)].map((m) => m[1]!).sort()
}

describe('artifacts/openscenario/openscenario.shacl.ttl — enum grounding', () => {
  it.each([
    ['vehicleCategory', 'VehicleCategory'],
    ['parameterType', 'ParameterType'],
    ['dynamicsShape', 'DynamicsShape'],
    ['dynamicsDimension', 'DynamicsDimension'],
  ])("%s matches the pinned ontology's %s owl:oneOf exactly", (propertyPath, datatypeLabel) => {
    expect(artifactEnum(propertyPath)).toEqual(pinnedEnum(datatypeLabel))
  })
})
